### ISSUE TITLE
Dynamic Arm Mode

### ISSUE THREAD

**Issue by jymeraz** [brownvc/SpotReality#5]
Dynamic arm mode should have spot's arm follow the movement of the joystick directly. This was implemented last semester. Last semester's work should be updated the the mode structure that was used over the summer. Modes should be fixed to differentiate between dynamic/static/manual arm.

**Comment by jymeraz** [comment]
Updated to mirror last semester's functionality, but can be updated for faster/smoother movement.

**Comment by jymeraz** [comment]
Note: Commands are sent immediately when the mode is entered, this should not happen. The way the dummy finger is displayed should be changed to make movement easier.

**Comment by nivlac12** [comment]
The location of the dummy hand does not seem to line up with the real world location, we should look into that.
![image](https://github.com/brownvc/SpotReality/assets/21201773/d80e809a-d6d3-4bff-848c-23dee53d4bd7)

**Comment by nivlac12** [comment]
Right now the arm unstows when we press trigger in any mode, it should probably only do that in dynamic arm mode.

**Comment by nivlac12** [comment]
Hand tracking gets very confusing when the dummy hand is pointing backward, we may need to update the relative transformations.

**Comment by nivlac12** [comment]
> Right now the arm unstows when we press trigger in any mode, it should probably only do that in dynamic arm mode.

I fixed this issue, the MoveArm script simply needed to be added to Static Arm Mode's "Scripts to Enable".

**Comment by nivlac12** [comment]
> Hand tracking gets very confusing when the dummy hand is pointing backward, we may need to update the relative transformations.

This was due to a relative rotation bug, was fixed in 62ddbcfbfafc4c7e16325d41a274574db0018a22.
